In [60]:
import geopandas as gpd
import pandas as pd

In [61]:
victoria_gdf = gpd.read_file('../data/Statistical_area_level2/victoria.geojson')

In [62]:
hospital_gdf = gpd.read_file('../data/external_SA2/Hospital.geojson')

In [63]:
joined_hospital = gpd.sjoin(hospital_gdf, victoria_gdf, how="inner", op="within")

/Users/ivysu/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py:3445: FutureWarning: The `op` parameter is deprecated and will be removed in a future release. Please use the `predicate` parameter instead.
  if await self.run_code(code, result, async_=asy):

In [64]:
joined_hospital.columns

Index(['id', '@id', 'addr:city', 'addr:country', 'addr:housename',
       'addr:housenumber', 'addr:postcode', 'addr:state', 'addr:street',
       'addr:suburb', 'amenity', 'building', 'contact:phone', 'cuisine',
       'designation', 'email', 'emergency', 'emergency_ward_entrance',
       'entrance', 'fax', 'fixme', 'health_amenity:type', 'healthcare',
       'healthcare:speciality', 'insurance:health', 'internet_access', 'name',
       'name:de', 'name:en', 'opening_hours', 'operator', 'operator:type',
       'phone', 'phone:AU', 'source', 'url', 'website', 'wheelchair',
       'wikidata', 'geometry', 'index_right', 'SA2_CODE21', 'SA2_NAME21',
       'CHG_FLAG21', 'CHG_LBL21', 'SA3_CODE21', 'SA3_NAME21', 'SA4_CODE21',
       'SA4_NAME21', 'GCC_CODE21', 'GCC_NAME21', 'STE_CODE21', 'STE_NAME21',
       'AUS_CODE21', 'AUS_NAME21', 'AREASQKM21', 'LOCI_URI21'],
      dtype='object')

In [65]:
hospital_SA2 = joined_hospital[['geometry', 'SA2_CODE21', 'SA2_NAME21']]

In [66]:
hospital_SA2 = hospital_SA2.rename(columns={'geometry': 'Hospital_geometry', 'SA2_CODE21': 'Hospital_SA2_Code', 'SA2_NAME21': 'Hospital_SA2_Name'})

In [67]:
#hospital_SA2.to_csv('../data/raw/hospital_SA2.csv', index=False)

In [68]:
school_df = pd.read_csv("../data/external_SA2/complete_school_location.csv", encoding='latin-1')
school_df['coordinates'] = school_df.apply(lambda row: [row['Y'], row['X']], axis=1)

In [69]:
import geopandas as gpd
from shapely.geometry import Point

# Your property data
school_metadata = school_df

# Convert the coordinates column to a suitable format (assuming it's a string like '[lat, lon]')
#school_metadata['coordinates'] = school_metadata['coordinates'].apply(eval)

# Create points and names from the property_metadata
coords = [Point(xy[1], xy[0]) for xy in school_metadata['coordinates']]
names = school_metadata['School_Type'].tolist()

# Convert to GeoDataFrame
school_gdf = gpd.GeoDataFrame({'name': names, 'geometry': coords})

In [70]:
joined_school = gpd.sjoin(school_gdf, victoria_gdf, how="inner", op="within")

/Users/ivysu/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py:3445: FutureWarning: The `op` parameter is deprecated and will be removed in a future release. Please use the `predicate` parameter instead.
  if await self.run_code(code, result, async_=asy):
/var/folders/38/85yvxj112kj5cp41m83y71800000gn/T/ipykernel_52953/2591452774.py:1: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:4326

  joined_school = gpd.sjoin(school_gdf, victoria_gdf, how="inner", op="within")

In [71]:
school_SA2 = joined_school[['name', 'geometry', 'SA2_CODE21', 'SA2_NAME21']]
school_SA2 = school_SA2.rename(columns={'name':'School_Type', 'geometry': 'School_Geometry', 'SA2_CODE21	': 'School_SA2_Code', 'SA2_NAME21': 'School_SA2_Name'})

In [72]:
hospital_SA2

              Hospital_geometry Hospital_SA2_Code        Hospital_SA2_Name
0   POINT (145.14557 -37.88438)         212051324   Mount Waverley - South
1   POINT (142.88089 -35.05114)         215031405      Swan Hill Surrounds
2   POINT (145.16495 -37.85261)         211041269              Forest Hill
16  POINT (145.16571 -37.83374)         211041269              Forest Hill
3   POINT (145.12244 -37.92082)         212051568        Clayton - Central
21  POINT (145.12067 -37.92190)         212051568        Clayton - Central
23  POINT (145.11940 -37.92153)         212051568        Clayton - Central
55  POINT (145.12025 -37.92090)         212051568        Clayton - Central
4   POINT (145.13820 -37.01852)         204011059                  Seymour
5   POINT (145.21272 -37.93804)         212051325                 Mulgrave
35  POINT (145.21315 -37.93867)         212051325                 Mulgrave
6   POINT (146.96597 -36.73296)         204031069    Bright - Mount Beauty
7   POINT (142.97650 -38.48607)         217031475      Corangamite - South
8   POINT (142.90206 -38.23939)         217031474      Corangamite - North
9   POINT (143.98042 -38.54544)         203031049         Lorne - Anglesea
10  POINT (144.83876 -37.86516)         213021341                   Altona
11  POINT (143.89176 -37.42009)         201021010        Creswick - Clunes
12  POINT (144.22244 -37.59953)         201021009  Bacchus Marsh Surrounds
13  POINT (145.06095 -37.75590)         209011198     Heidelberg - Rosanna
14  POINT (145.09401 -37.85690)         207011150         Glen Iris - East
15  POINT (146.78423 -37.97632)         205051101                   Maffra
17  POINT (149.75346 -37.55837)         205021085                   Orbost
18  POINT (145.23281 -38.46001)         205031091           Phillip Island
25  POINT (145.23725 -38.44949)         205031091           Phillip Island
19  POINT (144.95642 -37.79946)         206041124                Parkville
39  POINT (144.95622 -37.79993)         206041124                Parkville
40  POINT (144.95679 -37.80039)         206041124                Parkville
20  POINT (144.73249 -37.88430)         213051581  Point Cook - North West
22  POINT (144.94751 -37.72339)         210031538              Pascoe Vale
26  POINT (144.97171 -37.75681)         206011495        Brunswick - North
41  POINT (144.96581 -37.76631)         206011495        Brunswick - North
27  POINT (144.91315 -37.68433)         210051242             Broadmeadows
30  POINT (145.95413 -38.02196)         205011077     Mount Baw Baw Region
31  POINT (141.62407 -38.13795)         217011420           Glenelg (Vic.)
32  POINT (144.80656 -37.72362)         213011332             Keilor Downs
33  POINT (144.21234 -37.05191)         202021027              Castlemaine
34  POINT (145.04218 -36.31557)         216011407                  Kyabram
37  POINT (145.18593 -37.97522)         212041460        Noble Park - West
43  POINT (145.17383 -37.96768)         212041460        Noble Park - West
42  POINT (145.17732 -37.95231)         212041459        Noble Park - East
44  POINT (145.04190 -38.22382)         214021592        Mornington - West
45  POINT (144.28019 -36.74924)         202011018                  Bendigo
46  POINT (147.90306 -36.19876)         204031072                   Towong
48  POINT (145.02414 -37.87748)         208021177        Caulfield - North
49  POINT (142.02445 -36.44999)         215011390             Nhill Region
50  POINT (144.99401 -37.81682)         206071518         Richmond - North
51  POINT (145.40514 -36.36291)         216031416       Shepparton - North
53  POINT (145.35138 -37.75654)         211051278    Lilydale - Coldstream
54  POINT (145.24911 -37.84407)         211011251                Bayswater
56  POINT (145.13282 -37.78739)         207021157                Doncaster

In [73]:
school_SA2

,School_Type,School_Geometry,SA2_CODE21,School_SA2_Name
0,college,POINT (145.36439 -38.08443),212031555,Clyde North - North
1082,Primary,POINT (145.37283 -38.08273),212031555,Clyde North - North
2062,Pri/Sec,POINT (145.36380 -38.08468),212031555,Clyde North - North
2,college,POINT (143.85879 -37.56115),201011002,Ballarat
82,Primary,POINT (143.85394 -37.56401),201011002,Ballarat
...,...,...,...,...
2065,Pri/Sec,POINT (145.46732 -38.06190),212011550,Pakenham - North West
2213,Primary,POINT (145.43271 -38.06277),212011550,Pakenham - North West
2088,Pri/Sec,POINT (144.56028 -37.70028),213041571,Brookfield
2184,Pri/Sec,POINT (144.33707 -38.23046),203021485,Charlemont
2241,Secondary,POINT (144.35671 -38.21912),203021485,Charlemont

In [74]:
supermarket_gdf = gpd.read_file('../data/external_SA2/Supermarket.geojson')
joined_supermarket = gpd.sjoin(supermarket_gdf, victoria_gdf, how="inner", op="within")

/Users/ivysu/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py:3445: FutureWarning: The `op` parameter is deprecated and will be removed in a future release. Please use the `predicate` parameter instead.
  if await self.run_code(code, result, async_=asy):

In [75]:
supermarket_SA2 = joined_supermarket[['geometry', 'SA2_CODE21', 'SA2_NAME21']]
supermarket_SA2 = supermarket_SA2.rename(columns={'geometry': 'Supermarket_geometry', 'SA2_CODE21': 'Supermarket_SA2_Code', 'SA2_NAME21': 'Supermarket_SA2_Name'})

In [76]:
supermarket_SA2

,Supermarket_geometry,Supermarket_SA2_Code,Supermarket_SA2_Name
0,POINT (144.73386 -37.27736),210021235,Romsey
910,POINT (144.74143 -37.34796),210021235,Romsey
1,POINT (145.17184 -37.79143),207021425,Doncaster East - South
283,POINT (145.16103 -37.78871),207021425,Doncaster East - South
284,POINT (145.14832 -37.78797),207021425,Doncaster East - South
...,...,...,...
964,POINT (145.28730 -38.05163),212031458,Narre Warren South - West
967,POINT (145.10012 -37.60255),209041532,Mernda - South
970,POINT (144.72602 -37.71258),213041574,Fraser Rise - Plumpton
981,POINT (143.88527 -37.55962),201011481,Ballarat East - Warrenheip
984,POINT (144.35723 -36.80557),202011024,Strathfieldsaye